package com.airshiplay.play.website.model;

import java.io.Serializable;

/**
 *
 * database table shop_product_to_tag
 *
 * @date do_not_delete_during_merge
 */
public class ShopProductToTagKey implements Serializable {
    private Long products_id;

    private Long tags_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getProducts_id() {
        return products_id;
    }

    public void setProducts_id(Long products_id) {
        this.products_id = products_id;
    }

    public Long getTags_id() {
        return tags_id;
    }

    public void setTags_id(Long tags_id) {
        this.tags_id = tags_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShopProductToTagKey other = (ShopProductToTagKey) that;
        return (this.getProducts_id() == null ? other.getProducts_id() == null : this.getProducts_id().equals(other.getProducts_id()))
            && (this.getTags_id() == null ? other.getTags_id() == null : this.getTags_id().equals(other.getTags_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProducts_id() == null) ? 0 : getProducts_id().hashCode());
        result = prime * result + ((getTags_id() == null) ? 0 : getTags_id().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", products_id=").append(products_id);
        sb.append(", tags_id=").append(tags_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}