package com.airshiplay.play.website.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WechatMessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_message
     *
     * @date
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_message
     *
     * @date
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_message
     *
     * @date
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    public WechatMessageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * 
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameIsNull() {
            addCriterion("from_username is null");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameIsNotNull() {
            addCriterion("from_username is not null");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameEqualTo(String value) {
            addCriterion("from_username =", value, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameNotEqualTo(String value) {
            addCriterion("from_username <>", value, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameGreaterThan(String value) {
            addCriterion("from_username >", value, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameGreaterThanOrEqualTo(String value) {
            addCriterion("from_username >=", value, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameLessThan(String value) {
            addCriterion("from_username <", value, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameLessThanOrEqualTo(String value) {
            addCriterion("from_username <=", value, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameLike(String value) {
            addCriterion("from_username like", value, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameNotLike(String value) {
            addCriterion("from_username not like", value, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameIn(List<String> values) {
            addCriterion("from_username in", values, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameNotIn(List<String> values) {
            addCriterion("from_username not in", values, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameBetween(String value1, String value2) {
            addCriterion("from_username between", value1, value2, "from_username");
            return (Criteria) this;
        }

        public Criteria andFrom_usernameNotBetween(String value1, String value2) {
            addCriterion("from_username not between", value1, value2, "from_username");
            return (Criteria) this;
        }

        public Criteria andMsg_idIsNull() {
            addCriterion("msg_id is null");
            return (Criteria) this;
        }

        public Criteria andMsg_idIsNotNull() {
            addCriterion("msg_id is not null");
            return (Criteria) this;
        }

        public Criteria andMsg_idEqualTo(String value) {
            addCriterion("msg_id =", value, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idNotEqualTo(String value) {
            addCriterion("msg_id <>", value, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idGreaterThan(String value) {
            addCriterion("msg_id >", value, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idGreaterThanOrEqualTo(String value) {
            addCriterion("msg_id >=", value, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idLessThan(String value) {
            addCriterion("msg_id <", value, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idLessThanOrEqualTo(String value) {
            addCriterion("msg_id <=", value, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idLike(String value) {
            addCriterion("msg_id like", value, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idNotLike(String value) {
            addCriterion("msg_id not like", value, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idIn(List<String> values) {
            addCriterion("msg_id in", values, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idNotIn(List<String> values) {
            addCriterion("msg_id not in", values, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idBetween(String value1, String value2) {
            addCriterion("msg_id between", value1, value2, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_idNotBetween(String value1, String value2) {
            addCriterion("msg_id not between", value1, value2, "msg_id");
            return (Criteria) this;
        }

        public Criteria andMsg_typeIsNull() {
            addCriterion("msg_type is null");
            return (Criteria) this;
        }

        public Criteria andMsg_typeIsNotNull() {
            addCriterion("msg_type is not null");
            return (Criteria) this;
        }

        public Criteria andMsg_typeEqualTo(String value) {
            addCriterion("msg_type =", value, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeNotEqualTo(String value) {
            addCriterion("msg_type <>", value, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeGreaterThan(String value) {
            addCriterion("msg_type >", value, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeGreaterThanOrEqualTo(String value) {
            addCriterion("msg_type >=", value, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeLessThan(String value) {
            addCriterion("msg_type <", value, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeLessThanOrEqualTo(String value) {
            addCriterion("msg_type <=", value, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeLike(String value) {
            addCriterion("msg_type like", value, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeNotLike(String value) {
            addCriterion("msg_type not like", value, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeIn(List<String> values) {
            addCriterion("msg_type in", values, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeNotIn(List<String> values) {
            addCriterion("msg_type not in", values, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeBetween(String value1, String value2) {
            addCriterion("msg_type between", value1, value2, "msg_type");
            return (Criteria) this;
        }

        public Criteria andMsg_typeNotBetween(String value1, String value2) {
            addCriterion("msg_type not between", value1, value2, "msg_type");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("`timestamp` is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("`timestamp` is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Date value) {
            addCriterion("`timestamp` =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Date value) {
            addCriterion("`timestamp` <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Date value) {
            addCriterion("`timestamp` >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("`timestamp` >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Date value) {
            addCriterion("`timestamp` <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Date value) {
            addCriterion("`timestamp` <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Date> values) {
            addCriterion("`timestamp` in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Date> values) {
            addCriterion("`timestamp` not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Date value1, Date value2) {
            addCriterion("`timestamp` between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Date value1, Date value2) {
            addCriterion("`timestamp` not between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTo_usernameIsNull() {
            addCriterion("to_username is null");
            return (Criteria) this;
        }

        public Criteria andTo_usernameIsNotNull() {
            addCriterion("to_username is not null");
            return (Criteria) this;
        }

        public Criteria andTo_usernameEqualTo(String value) {
            addCriterion("to_username =", value, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameNotEqualTo(String value) {
            addCriterion("to_username <>", value, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameGreaterThan(String value) {
            addCriterion("to_username >", value, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameGreaterThanOrEqualTo(String value) {
            addCriterion("to_username >=", value, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameLessThan(String value) {
            addCriterion("to_username <", value, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameLessThanOrEqualTo(String value) {
            addCriterion("to_username <=", value, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameLike(String value) {
            addCriterion("to_username like", value, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameNotLike(String value) {
            addCriterion("to_username not like", value, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameIn(List<String> values) {
            addCriterion("to_username in", values, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameNotIn(List<String> values) {
            addCriterion("to_username not in", values, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameBetween(String value1, String value2) {
            addCriterion("to_username between", value1, value2, "to_username");
            return (Criteria) this;
        }

        public Criteria andTo_usernameNotBetween(String value1, String value2) {
            addCriterion("to_username not between", value1, value2, "to_username");
            return (Criteria) this;
        }

        public Criteria andConfig_idIsNull() {
            addCriterion("config_id is null");
            return (Criteria) this;
        }

        public Criteria andConfig_idIsNotNull() {
            addCriterion("config_id is not null");
            return (Criteria) this;
        }

        public Criteria andConfig_idEqualTo(Long value) {
            addCriterion("config_id =", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idNotEqualTo(Long value) {
            addCriterion("config_id <>", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idGreaterThan(Long value) {
            addCriterion("config_id >", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idGreaterThanOrEqualTo(Long value) {
            addCriterion("config_id >=", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idLessThan(Long value) {
            addCriterion("config_id <", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idLessThanOrEqualTo(Long value) {
            addCriterion("config_id <=", value, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idIn(List<Long> values) {
            addCriterion("config_id in", values, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idNotIn(List<Long> values) {
            addCriterion("config_id not in", values, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idBetween(Long value1, Long value2) {
            addCriterion("config_id between", value1, value2, "config_id");
            return (Criteria) this;
        }

        public Criteria andConfig_idNotBetween(Long value1, Long value2) {
            addCriterion("config_id not between", value1, value2, "config_id");
            return (Criteria) this;
        }

        public Criteria andAttention_uidIsNull() {
            addCriterion("attention_uid is null");
            return (Criteria) this;
        }

        public Criteria andAttention_uidIsNotNull() {
            addCriterion("attention_uid is not null");
            return (Criteria) this;
        }

        public Criteria andAttention_uidEqualTo(Long value) {
            addCriterion("attention_uid =", value, "attention_uid");
            return (Criteria) this;
        }

        public Criteria andAttention_uidNotEqualTo(Long value) {
            addCriterion("attention_uid <>", value, "attention_uid");
            return (Criteria) this;
        }

        public Criteria andAttention_uidGreaterThan(Long value) {
            addCriterion("attention_uid >", value, "attention_uid");
            return (Criteria) this;
        }

        public Criteria andAttention_uidGreaterThanOrEqualTo(Long value) {
            addCriterion("attention_uid >=", value, "attention_uid");
            return (Criteria) this;
        }

        public Criteria andAttention_uidLessThan(Long value) {
            addCriterion("attention_uid <", value, "attention_uid");
            return (Criteria) this;
        }

        public Criteria andAttention_uidLessThanOrEqualTo(Long value) {
            addCriterion("attention_uid <=", value, "attention_uid");
            return (Criteria) this;
        }

        public Criteria andAttention_uidIn(List<Long> values) {
            addCriterion("attention_uid in", values, "attention_uid");
            return (Criteria) this;
        }

        public Criteria andAttention_uidNotIn(List<Long> values) {
            addCriterion("attention_uid not in", values, "attention_uid");
            return (Criteria) this;
        }

        public Criteria andAttention_uidBetween(Long value1, Long value2) {
            addCriterion("attention_uid between", value1, value2, "attention_uid");
            return (Criteria) this;
        }

        public Criteria andAttention_uidNotBetween(Long value1, Long value2) {
            addCriterion("attention_uid not between", value1, value2, "attention_uid");
            return (Criteria) this;
        }
    }

    /**
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}