package com.airshiplay.play.website.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * database table wechat_card_coupon_member
 *
 * @date do_not_delete_during_merge
 */
public class WechatCardCouponMember implements Serializable {
    private Long id;

    private Date createdDate;

    private Date lastModifiedDate;

    private String backgroudUrl;

    private String brandName;

    private String cardId;

    private String color;

    private Integer cost_bonus_unit;

    private Integer cost_money_unit;

    private String description;

    private Integer discount;

    private Integer increase_bonus;

    private Integer init_increase_bonus;

    private Integer least_money_to_use_bonus;

    private String logoUrl;

    private Integer max_increase_bonus;

    private Integer max_reduce_bonus;

    private String notice;

    private String prerogative;

    private Integer reduce_money;

    private String servicePhone;

    private Long sku_quantity;

    private String title;

    private Long createdBy_id;

    private Long lastModifiedBy_id;

    private Long card_coupon_id;

    private String activateUrl;

    private Long sku_surplusQuantity;

    private String status;

    private String activate_url;

    private String card_id;

    private String wxbackgroudUrl;

    private String wxlogoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public String getBackgroudUrl() {
        return backgroudUrl;
    }

    public void setBackgroudUrl(String backgroudUrl) {
        this.backgroudUrl = backgroudUrl == null ? null : backgroudUrl.trim();
    }

    public String getBrandName() {
        return brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    public String getCardId() {
        return cardId;
    }

    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    public Integer getCost_bonus_unit() {
        return cost_bonus_unit;
    }

    public void setCost_bonus_unit(Integer cost_bonus_unit) {
        this.cost_bonus_unit = cost_bonus_unit;
    }

    public Integer getCost_money_unit() {
        return cost_money_unit;
    }

    public void setCost_money_unit(Integer cost_money_unit) {
        this.cost_money_unit = cost_money_unit;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public Integer getDiscount() {
        return discount;
    }

    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    public Integer getIncrease_bonus() {
        return increase_bonus;
    }

    public void setIncrease_bonus(Integer increase_bonus) {
        this.increase_bonus = increase_bonus;
    }

    public Integer getInit_increase_bonus() {
        return init_increase_bonus;
    }

    public void setInit_increase_bonus(Integer init_increase_bonus) {
        this.init_increase_bonus = init_increase_bonus;
    }

    public Integer getLeast_money_to_use_bonus() {
        return least_money_to_use_bonus;
    }

    public void setLeast_money_to_use_bonus(Integer least_money_to_use_bonus) {
        this.least_money_to_use_bonus = least_money_to_use_bonus;
    }

    public String getLogoUrl() {
        return logoUrl;
    }

    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    public Integer getMax_increase_bonus() {
        return max_increase_bonus;
    }

    public void setMax_increase_bonus(Integer max_increase_bonus) {
        this.max_increase_bonus = max_increase_bonus;
    }

    public Integer getMax_reduce_bonus() {
        return max_reduce_bonus;
    }

    public void setMax_reduce_bonus(Integer max_reduce_bonus) {
        this.max_reduce_bonus = max_reduce_bonus;
    }

    public String getNotice() {
        return notice;
    }

    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    public String getPrerogative() {
        return prerogative;
    }

    public void setPrerogative(String prerogative) {
        this.prerogative = prerogative == null ? null : prerogative.trim();
    }

    public Integer getReduce_money() {
        return reduce_money;
    }

    public void setReduce_money(Integer reduce_money) {
        this.reduce_money = reduce_money;
    }

    public String getServicePhone() {
        return servicePhone;
    }

    public void setServicePhone(String servicePhone) {
        this.servicePhone = servicePhone == null ? null : servicePhone.trim();
    }

    public Long getSku_quantity() {
        return sku_quantity;
    }

    public void setSku_quantity(Long sku_quantity) {
        this.sku_quantity = sku_quantity;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    public Long getCreatedBy_id() {
        return createdBy_id;
    }

    public void setCreatedBy_id(Long createdBy_id) {
        this.createdBy_id = createdBy_id;
    }

    public Long getLastModifiedBy_id() {
        return lastModifiedBy_id;
    }

    public void setLastModifiedBy_id(Long lastModifiedBy_id) {
        this.lastModifiedBy_id = lastModifiedBy_id;
    }

    public Long getCard_coupon_id() {
        return card_coupon_id;
    }

    public void setCard_coupon_id(Long card_coupon_id) {
        this.card_coupon_id = card_coupon_id;
    }

    public String getActivateUrl() {
        return activateUrl;
    }

    public void setActivateUrl(String activateUrl) {
        this.activateUrl = activateUrl == null ? null : activateUrl.trim();
    }

    public Long getSku_surplusQuantity() {
        return sku_surplusQuantity;
    }

    public void setSku_surplusQuantity(Long sku_surplusQuantity) {
        this.sku_surplusQuantity = sku_surplusQuantity;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public String getActivate_url() {
        return activate_url;
    }

    public void setActivate_url(String activate_url) {
        this.activate_url = activate_url == null ? null : activate_url.trim();
    }

    public String getCard_id() {
        return card_id;
    }

    public void setCard_id(String card_id) {
        this.card_id = card_id == null ? null : card_id.trim();
    }

    public String getWxbackgroudUrl() {
        return wxbackgroudUrl;
    }

    public void setWxbackgroudUrl(String wxbackgroudUrl) {
        this.wxbackgroudUrl = wxbackgroudUrl == null ? null : wxbackgroudUrl.trim();
    }

    public String getWxlogoUrl() {
        return wxlogoUrl;
    }

    public void setWxlogoUrl(String wxlogoUrl) {
        this.wxlogoUrl = wxlogoUrl == null ? null : wxlogoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WechatCardCouponMember other = (WechatCardCouponMember) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getLastModifiedDate() == null ? other.getLastModifiedDate() == null : this.getLastModifiedDate().equals(other.getLastModifiedDate()))
            && (this.getBackgroudUrl() == null ? other.getBackgroudUrl() == null : this.getBackgroudUrl().equals(other.getBackgroudUrl()))
            && (this.getBrandName() == null ? other.getBrandName() == null : this.getBrandName().equals(other.getBrandName()))
            && (this.getCardId() == null ? other.getCardId() == null : this.getCardId().equals(other.getCardId()))
            && (this.getColor() == null ? other.getColor() == null : this.getColor().equals(other.getColor()))
            && (this.getCost_bonus_unit() == null ? other.getCost_bonus_unit() == null : this.getCost_bonus_unit().equals(other.getCost_bonus_unit()))
            && (this.getCost_money_unit() == null ? other.getCost_money_unit() == null : this.getCost_money_unit().equals(other.getCost_money_unit()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getDiscount() == null ? other.getDiscount() == null : this.getDiscount().equals(other.getDiscount()))
            && (this.getIncrease_bonus() == null ? other.getIncrease_bonus() == null : this.getIncrease_bonus().equals(other.getIncrease_bonus()))
            && (this.getInit_increase_bonus() == null ? other.getInit_increase_bonus() == null : this.getInit_increase_bonus().equals(other.getInit_increase_bonus()))
            && (this.getLeast_money_to_use_bonus() == null ? other.getLeast_money_to_use_bonus() == null : this.getLeast_money_to_use_bonus().equals(other.getLeast_money_to_use_bonus()))
            && (this.getLogoUrl() == null ? other.getLogoUrl() == null : this.getLogoUrl().equals(other.getLogoUrl()))
            && (this.getMax_increase_bonus() == null ? other.getMax_increase_bonus() == null : this.getMax_increase_bonus().equals(other.getMax_increase_bonus()))
            && (this.getMax_reduce_bonus() == null ? other.getMax_reduce_bonus() == null : this.getMax_reduce_bonus().equals(other.getMax_reduce_bonus()))
            && (this.getNotice() == null ? other.getNotice() == null : this.getNotice().equals(other.getNotice()))
            && (this.getPrerogative() == null ? other.getPrerogative() == null : this.getPrerogative().equals(other.getPrerogative()))
            && (this.getReduce_money() == null ? other.getReduce_money() == null : this.getReduce_money().equals(other.getReduce_money()))
            && (this.getServicePhone() == null ? other.getServicePhone() == null : this.getServicePhone().equals(other.getServicePhone()))
            && (this.getSku_quantity() == null ? other.getSku_quantity() == null : this.getSku_quantity().equals(other.getSku_quantity()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getCreatedBy_id() == null ? other.getCreatedBy_id() == null : this.getCreatedBy_id().equals(other.getCreatedBy_id()))
            && (this.getLastModifiedBy_id() == null ? other.getLastModifiedBy_id() == null : this.getLastModifiedBy_id().equals(other.getLastModifiedBy_id()))
            && (this.getCard_coupon_id() == null ? other.getCard_coupon_id() == null : this.getCard_coupon_id().equals(other.getCard_coupon_id()))
            && (this.getActivateUrl() == null ? other.getActivateUrl() == null : this.getActivateUrl().equals(other.getActivateUrl()))
            && (this.getSku_surplusQuantity() == null ? other.getSku_surplusQuantity() == null : this.getSku_surplusQuantity().equals(other.getSku_surplusQuantity()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getActivate_url() == null ? other.getActivate_url() == null : this.getActivate_url().equals(other.getActivate_url()))
            && (this.getCard_id() == null ? other.getCard_id() == null : this.getCard_id().equals(other.getCard_id()))
            && (this.getWxbackgroudUrl() == null ? other.getWxbackgroudUrl() == null : this.getWxbackgroudUrl().equals(other.getWxbackgroudUrl()))
            && (this.getWxlogoUrl() == null ? other.getWxlogoUrl() == null : this.getWxlogoUrl().equals(other.getWxlogoUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getLastModifiedDate() == null) ? 0 : getLastModifiedDate().hashCode());
        result = prime * result + ((getBackgroudUrl() == null) ? 0 : getBackgroudUrl().hashCode());
        result = prime * result + ((getBrandName() == null) ? 0 : getBrandName().hashCode());
        result = prime * result + ((getCardId() == null) ? 0 : getCardId().hashCode());
        result = prime * result + ((getColor() == null) ? 0 : getColor().hashCode());
        result = prime * result + ((getCost_bonus_unit() == null) ? 0 : getCost_bonus_unit().hashCode());
        result = prime * result + ((getCost_money_unit() == null) ? 0 : getCost_money_unit().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getDiscount() == null) ? 0 : getDiscount().hashCode());
        result = prime * result + ((getIncrease_bonus() == null) ? 0 : getIncrease_bonus().hashCode());
        result = prime * result + ((getInit_increase_bonus() == null) ? 0 : getInit_increase_bonus().hashCode());
        result = prime * result + ((getLeast_money_to_use_bonus() == null) ? 0 : getLeast_money_to_use_bonus().hashCode());
        result = prime * result + ((getLogoUrl() == null) ? 0 : getLogoUrl().hashCode());
        result = prime * result + ((getMax_increase_bonus() == null) ? 0 : getMax_increase_bonus().hashCode());
        result = prime * result + ((getMax_reduce_bonus() == null) ? 0 : getMax_reduce_bonus().hashCode());
        result = prime * result + ((getNotice() == null) ? 0 : getNotice().hashCode());
        result = prime * result + ((getPrerogative() == null) ? 0 : getPrerogative().hashCode());
        result = prime * result + ((getReduce_money() == null) ? 0 : getReduce_money().hashCode());
        result = prime * result + ((getServicePhone() == null) ? 0 : getServicePhone().hashCode());
        result = prime * result + ((getSku_quantity() == null) ? 0 : getSku_quantity().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getCreatedBy_id() == null) ? 0 : getCreatedBy_id().hashCode());
        result = prime * result + ((getLastModifiedBy_id() == null) ? 0 : getLastModifiedBy_id().hashCode());
        result = prime * result + ((getCard_coupon_id() == null) ? 0 : getCard_coupon_id().hashCode());
        result = prime * result + ((getActivateUrl() == null) ? 0 : getActivateUrl().hashCode());
        result = prime * result + ((getSku_surplusQuantity() == null) ? 0 : getSku_surplusQuantity().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getActivate_url() == null) ? 0 : getActivate_url().hashCode());
        result = prime * result + ((getCard_id() == null) ? 0 : getCard_id().hashCode());
        result = prime * result + ((getWxbackgroudUrl() == null) ? 0 : getWxbackgroudUrl().hashCode());
        result = prime * result + ((getWxlogoUrl() == null) ? 0 : getWxlogoUrl().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", lastModifiedDate=").append(lastModifiedDate);
        sb.append(", backgroudUrl=").append(backgroudUrl);
        sb.append(", brandName=").append(brandName);
        sb.append(", cardId=").append(cardId);
        sb.append(", color=").append(color);
        sb.append(", cost_bonus_unit=").append(cost_bonus_unit);
        sb.append(", cost_money_unit=").append(cost_money_unit);
        sb.append(", description=").append(description);
        sb.append(", discount=").append(discount);
        sb.append(", increase_bonus=").append(increase_bonus);
        sb.append(", init_increase_bonus=").append(init_increase_bonus);
        sb.append(", least_money_to_use_bonus=").append(least_money_to_use_bonus);
        sb.append(", logoUrl=").append(logoUrl);
        sb.append(", max_increase_bonus=").append(max_increase_bonus);
        sb.append(", max_reduce_bonus=").append(max_reduce_bonus);
        sb.append(", notice=").append(notice);
        sb.append(", prerogative=").append(prerogative);
        sb.append(", reduce_money=").append(reduce_money);
        sb.append(", servicePhone=").append(servicePhone);
        sb.append(", sku_quantity=").append(sku_quantity);
        sb.append(", title=").append(title);
        sb.append(", createdBy_id=").append(createdBy_id);
        sb.append(", lastModifiedBy_id=").append(lastModifiedBy_id);
        sb.append(", card_coupon_id=").append(card_coupon_id);
        sb.append(", activateUrl=").append(activateUrl);
        sb.append(", sku_surplusQuantity=").append(sku_surplusQuantity);
        sb.append(", status=").append(status);
        sb.append(", activate_url=").append(activate_url);
        sb.append(", card_id=").append(card_id);
        sb.append(", wxbackgroudUrl=").append(wxbackgroudUrl);
        sb.append(", wxlogoUrl=").append(wxlogoUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}