package com.airshiplay.play.website.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * database table wechat_attention_reply
 *
 * @date do_not_delete_during_merge
 */
public class WechatAttentionReply implements Serializable {
    private Long id;

    private Date createdDate;

    private Date lastModifiedDate;

    private Integer msgType;

    private Long createdBy_id;

    private Long lastModifiedBy_id;

    private Long config_id;

    private Long imageText_id;

    private Long text_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public Integer getMsgType() {
        return msgType;
    }

    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    public Long getCreatedBy_id() {
        return createdBy_id;
    }

    public void setCreatedBy_id(Long createdBy_id) {
        this.createdBy_id = createdBy_id;
    }

    public Long getLastModifiedBy_id() {
        return lastModifiedBy_id;
    }

    public void setLastModifiedBy_id(Long lastModifiedBy_id) {
        this.lastModifiedBy_id = lastModifiedBy_id;
    }

    public Long getConfig_id() {
        return config_id;
    }

    public void setConfig_id(Long config_id) {
        this.config_id = config_id;
    }

    public Long getImageText_id() {
        return imageText_id;
    }

    public void setImageText_id(Long imageText_id) {
        this.imageText_id = imageText_id;
    }

    public Long getText_id() {
        return text_id;
    }

    public void setText_id(Long text_id) {
        this.text_id = text_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WechatAttentionReply other = (WechatAttentionReply) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getLastModifiedDate() == null ? other.getLastModifiedDate() == null : this.getLastModifiedDate().equals(other.getLastModifiedDate()))
            && (this.getMsgType() == null ? other.getMsgType() == null : this.getMsgType().equals(other.getMsgType()))
            && (this.getCreatedBy_id() == null ? other.getCreatedBy_id() == null : this.getCreatedBy_id().equals(other.getCreatedBy_id()))
            && (this.getLastModifiedBy_id() == null ? other.getLastModifiedBy_id() == null : this.getLastModifiedBy_id().equals(other.getLastModifiedBy_id()))
            && (this.getConfig_id() == null ? other.getConfig_id() == null : this.getConfig_id().equals(other.getConfig_id()))
            && (this.getImageText_id() == null ? other.getImageText_id() == null : this.getImageText_id().equals(other.getImageText_id()))
            && (this.getText_id() == null ? other.getText_id() == null : this.getText_id().equals(other.getText_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getLastModifiedDate() == null) ? 0 : getLastModifiedDate().hashCode());
        result = prime * result + ((getMsgType() == null) ? 0 : getMsgType().hashCode());
        result = prime * result + ((getCreatedBy_id() == null) ? 0 : getCreatedBy_id().hashCode());
        result = prime * result + ((getLastModifiedBy_id() == null) ? 0 : getLastModifiedBy_id().hashCode());
        result = prime * result + ((getConfig_id() == null) ? 0 : getConfig_id().hashCode());
        result = prime * result + ((getImageText_id() == null) ? 0 : getImageText_id().hashCode());
        result = prime * result + ((getText_id() == null) ? 0 : getText_id().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", lastModifiedDate=").append(lastModifiedDate);
        sb.append(", msgType=").append(msgType);
        sb.append(", createdBy_id=").append(createdBy_id);
        sb.append(", lastModifiedBy_id=").append(lastModifiedBy_id);
        sb.append(", config_id=").append(config_id);
        sb.append(", imageText_id=").append(imageText_id);
        sb.append(", text_id=").append(text_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}