package com.airshiplay.play.website.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * database table wechat_attention_subscribe
 *
 * @date do_not_delete_during_merge
 */
public class WechatAttentionSubscribe implements Serializable {
    private Long id;

    private Integer status;

    private Date subscribeTime;

    private Long attention_uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_attention_subscribe
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getSubscribeTime() {
        return subscribeTime;
    }

    public void setSubscribeTime(Date subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    public Long getAttention_uid() {
        return attention_uid;
    }

    public void setAttention_uid(Long attention_uid) {
        this.attention_uid = attention_uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_subscribe
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WechatAttentionSubscribe other = (WechatAttentionSubscribe) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getSubscribeTime() == null ? other.getSubscribeTime() == null : this.getSubscribeTime().equals(other.getSubscribeTime()))
            && (this.getAttention_uid() == null ? other.getAttention_uid() == null : this.getAttention_uid().equals(other.getAttention_uid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_subscribe
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getSubscribeTime() == null) ? 0 : getSubscribeTime().hashCode());
        result = prime * result + ((getAttention_uid() == null) ? 0 : getAttention_uid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_subscribe
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", status=").append(status);
        sb.append(", subscribeTime=").append(subscribeTime);
        sb.append(", attention_uid=").append(attention_uid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}