package com.airlenet.play.website.model;

import java.io.Serializable;

/**
 * database table cms_article_to_tag
 *
 * @date do_not_delete_during_merge
 */
public class CmsArticleToTagKey implements Serializable {
    private Long articles_id;

    private Long tags_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getArticles_id() {
        return articles_id;
    }

    public void setArticles_id(Long articles_id) {
        this.articles_id = articles_id;
    }

    public Long getTags_id() {
        return tags_id;
    }

    public void setTags_id(Long tags_id) {
        this.tags_id = tags_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CmsArticleToTagKey other = (CmsArticleToTagKey) that;
        return (this.getArticles_id() == null ? other.getArticles_id() == null : this.getArticles_id().equals(other.getArticles_id()))
                && (this.getTags_id() == null ? other.getTags_id() == null : this.getTags_id().equals(other.getTags_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getArticles_id() == null) ? 0 : getArticles_id().hashCode());
        result = prime * result + ((getTags_id() == null) ? 0 : getTags_id().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articles_id=").append(articles_id);
        sb.append(", tags_id=").append(tags_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}