package com.airlenet.play.website.model;

import java.io.Serializable;

/**
 * database table tbl_plugin_config_attribute
 *
 * @date do_not_delete_during_merge
 */
public class TblPluginConfigAttributeKey implements Serializable {
    private Long pluginConfigEntity_id;

    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getPluginConfigEntity_id() {
        return pluginConfigEntity_id;
    }

    public void setPluginConfigEntity_id(Long pluginConfigEntity_id) {
        this.pluginConfigEntity_id = pluginConfigEntity_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TblPluginConfigAttributeKey other = (TblPluginConfigAttributeKey) that;
        return (this.getPluginConfigEntity_id() == null ? other.getPluginConfigEntity_id() == null : this.getPluginConfigEntity_id().equals(other.getPluginConfigEntity_id()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPluginConfigEntity_id() == null) ? 0 : getPluginConfigEntity_id().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pluginConfigEntity_id=").append(pluginConfigEntity_id);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}