package com.airlenet.play.website.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WechatCardCouponMemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    public WechatCardCouponMemberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     *
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("createdDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("createdDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("createdDate =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("createdDate <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("createdDate >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdDate >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("createdDate <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("createdDate <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("createdDate in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("createdDate not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("createdDate between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("createdDate not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("lastModifiedDate is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("lastModifiedDate is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(Date value) {
            addCriterion("lastModifiedDate =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(Date value) {
            addCriterion("lastModifiedDate <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(Date value) {
            addCriterion("lastModifiedDate >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("lastModifiedDate >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(Date value) {
            addCriterion("lastModifiedDate <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("lastModifiedDate <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<Date> values) {
            addCriterion("lastModifiedDate in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<Date> values) {
            addCriterion("lastModifiedDate not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
            addCriterion("lastModifiedDate between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("lastModifiedDate not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlIsNull() {
            addCriterion("backgroudUrl is null");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlIsNotNull() {
            addCriterion("backgroudUrl is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlEqualTo(String value) {
            addCriterion("backgroudUrl =", value, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlNotEqualTo(String value) {
            addCriterion("backgroudUrl <>", value, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlGreaterThan(String value) {
            addCriterion("backgroudUrl >", value, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlGreaterThanOrEqualTo(String value) {
            addCriterion("backgroudUrl >=", value, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlLessThan(String value) {
            addCriterion("backgroudUrl <", value, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlLessThanOrEqualTo(String value) {
            addCriterion("backgroudUrl <=", value, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlLike(String value) {
            addCriterion("backgroudUrl like", value, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlNotLike(String value) {
            addCriterion("backgroudUrl not like", value, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlIn(List<String> values) {
            addCriterion("backgroudUrl in", values, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlNotIn(List<String> values) {
            addCriterion("backgroudUrl not in", values, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlBetween(String value1, String value2) {
            addCriterion("backgroudUrl between", value1, value2, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroudUrlNotBetween(String value1, String value2) {
            addCriterion("backgroudUrl not between", value1, value2, "backgroudUrl");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNull() {
            addCriterion("brandName is null");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNotNull() {
            addCriterion("brandName is not null");
            return (Criteria) this;
        }

        public Criteria andBrandNameEqualTo(String value) {
            addCriterion("brandName =", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotEqualTo(String value) {
            addCriterion("brandName <>", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThan(String value) {
            addCriterion("brandName >", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
            addCriterion("brandName >=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThan(String value) {
            addCriterion("brandName <", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThanOrEqualTo(String value) {
            addCriterion("brandName <=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLike(String value) {
            addCriterion("brandName like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotLike(String value) {
            addCriterion("brandName not like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameIn(List<String> values) {
            addCriterion("brandName in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotIn(List<String> values) {
            addCriterion("brandName not in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameBetween(String value1, String value2) {
            addCriterion("brandName between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotBetween(String value1, String value2) {
            addCriterion("brandName not between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNull() {
            addCriterion("cardId is null");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNotNull() {
            addCriterion("cardId is not null");
            return (Criteria) this;
        }

        public Criteria andCardIdEqualTo(String value) {
            addCriterion("cardId =", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotEqualTo(String value) {
            addCriterion("cardId <>", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThan(String value) {
            addCriterion("cardId >", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("cardId >=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThan(String value) {
            addCriterion("cardId <", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThanOrEqualTo(String value) {
            addCriterion("cardId <=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLike(String value) {
            addCriterion("cardId like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotLike(String value) {
            addCriterion("cardId not like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdIn(List<String> values) {
            addCriterion("cardId in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotIn(List<String> values) {
            addCriterion("cardId not in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdBetween(String value1, String value2) {
            addCriterion("cardId between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotBetween(String value1, String value2) {
            addCriterion("cardId not between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andColorIsNull() {
            addCriterion("color is null");
            return (Criteria) this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("color is not null");
            return (Criteria) this;
        }

        public Criteria andColorEqualTo(String value) {
            addCriterion("color =", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotEqualTo(String value) {
            addCriterion("color <>", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThan(String value) {
            addCriterion("color >", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThanOrEqualTo(String value) {
            addCriterion("color >=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThan(String value) {
            addCriterion("color <", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThanOrEqualTo(String value) {
            addCriterion("color <=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLike(String value) {
            addCriterion("color like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotLike(String value) {
            addCriterion("color not like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorIn(List<String> values) {
            addCriterion("color in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotIn(List<String> values) {
            addCriterion("color not in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorBetween(String value1, String value2) {
            addCriterion("color between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotBetween(String value1, String value2) {
            addCriterion("color not between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitIsNull() {
            addCriterion("cost_bonus_unit is null");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitIsNotNull() {
            addCriterion("cost_bonus_unit is not null");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitEqualTo(Integer value) {
            addCriterion("cost_bonus_unit =", value, "cost_bonus_unit");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitNotEqualTo(Integer value) {
            addCriterion("cost_bonus_unit <>", value, "cost_bonus_unit");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitGreaterThan(Integer value) {
            addCriterion("cost_bonus_unit >", value, "cost_bonus_unit");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitGreaterThanOrEqualTo(Integer value) {
            addCriterion("cost_bonus_unit >=", value, "cost_bonus_unit");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitLessThan(Integer value) {
            addCriterion("cost_bonus_unit <", value, "cost_bonus_unit");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitLessThanOrEqualTo(Integer value) {
            addCriterion("cost_bonus_unit <=", value, "cost_bonus_unit");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitIn(List<Integer> values) {
            addCriterion("cost_bonus_unit in", values, "cost_bonus_unit");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitNotIn(List<Integer> values) {
            addCriterion("cost_bonus_unit not in", values, "cost_bonus_unit");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitBetween(Integer value1, Integer value2) {
            addCriterion("cost_bonus_unit between", value1, value2, "cost_bonus_unit");
            return (Criteria) this;
        }

        public Criteria andCost_bonus_unitNotBetween(Integer value1, Integer value2) {
            addCriterion("cost_bonus_unit not between", value1, value2, "cost_bonus_unit");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitIsNull() {
            addCriterion("cost_money_unit is null");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitIsNotNull() {
            addCriterion("cost_money_unit is not null");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitEqualTo(Integer value) {
            addCriterion("cost_money_unit =", value, "cost_money_unit");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitNotEqualTo(Integer value) {
            addCriterion("cost_money_unit <>", value, "cost_money_unit");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitGreaterThan(Integer value) {
            addCriterion("cost_money_unit >", value, "cost_money_unit");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitGreaterThanOrEqualTo(Integer value) {
            addCriterion("cost_money_unit >=", value, "cost_money_unit");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitLessThan(Integer value) {
            addCriterion("cost_money_unit <", value, "cost_money_unit");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitLessThanOrEqualTo(Integer value) {
            addCriterion("cost_money_unit <=", value, "cost_money_unit");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitIn(List<Integer> values) {
            addCriterion("cost_money_unit in", values, "cost_money_unit");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitNotIn(List<Integer> values) {
            addCriterion("cost_money_unit not in", values, "cost_money_unit");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitBetween(Integer value1, Integer value2) {
            addCriterion("cost_money_unit between", value1, value2, "cost_money_unit");
            return (Criteria) this;
        }

        public Criteria andCost_money_unitNotBetween(Integer value1, Integer value2) {
            addCriterion("cost_money_unit not between", value1, value2, "cost_money_unit");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNull() {
            addCriterion("discount is null");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNotNull() {
            addCriterion("discount is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountEqualTo(Integer value) {
            addCriterion("discount =", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotEqualTo(Integer value) {
            addCriterion("discount <>", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThan(Integer value) {
            addCriterion("discount >", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThanOrEqualTo(Integer value) {
            addCriterion("discount >=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThan(Integer value) {
            addCriterion("discount <", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThanOrEqualTo(Integer value) {
            addCriterion("discount <=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountIn(List<Integer> values) {
            addCriterion("discount in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotIn(List<Integer> values) {
            addCriterion("discount not in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountBetween(Integer value1, Integer value2) {
            addCriterion("discount between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotBetween(Integer value1, Integer value2) {
            addCriterion("discount not between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusIsNull() {
            addCriterion("increase_bonus is null");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusIsNotNull() {
            addCriterion("increase_bonus is not null");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusEqualTo(Integer value) {
            addCriterion("increase_bonus =", value, "increase_bonus");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusNotEqualTo(Integer value) {
            addCriterion("increase_bonus <>", value, "increase_bonus");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusGreaterThan(Integer value) {
            addCriterion("increase_bonus >", value, "increase_bonus");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusGreaterThanOrEqualTo(Integer value) {
            addCriterion("increase_bonus >=", value, "increase_bonus");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusLessThan(Integer value) {
            addCriterion("increase_bonus <", value, "increase_bonus");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusLessThanOrEqualTo(Integer value) {
            addCriterion("increase_bonus <=", value, "increase_bonus");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusIn(List<Integer> values) {
            addCriterion("increase_bonus in", values, "increase_bonus");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusNotIn(List<Integer> values) {
            addCriterion("increase_bonus not in", values, "increase_bonus");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusBetween(Integer value1, Integer value2) {
            addCriterion("increase_bonus between", value1, value2, "increase_bonus");
            return (Criteria) this;
        }

        public Criteria andIncrease_bonusNotBetween(Integer value1, Integer value2) {
            addCriterion("increase_bonus not between", value1, value2, "increase_bonus");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusIsNull() {
            addCriterion("init_increase_bonus is null");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusIsNotNull() {
            addCriterion("init_increase_bonus is not null");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusEqualTo(Integer value) {
            addCriterion("init_increase_bonus =", value, "init_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusNotEqualTo(Integer value) {
            addCriterion("init_increase_bonus <>", value, "init_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusGreaterThan(Integer value) {
            addCriterion("init_increase_bonus >", value, "init_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusGreaterThanOrEqualTo(Integer value) {
            addCriterion("init_increase_bonus >=", value, "init_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusLessThan(Integer value) {
            addCriterion("init_increase_bonus <", value, "init_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusLessThanOrEqualTo(Integer value) {
            addCriterion("init_increase_bonus <=", value, "init_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusIn(List<Integer> values) {
            addCriterion("init_increase_bonus in", values, "init_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusNotIn(List<Integer> values) {
            addCriterion("init_increase_bonus not in", values, "init_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusBetween(Integer value1, Integer value2) {
            addCriterion("init_increase_bonus between", value1, value2, "init_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andInit_increase_bonusNotBetween(Integer value1, Integer value2) {
            addCriterion("init_increase_bonus not between", value1, value2, "init_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusIsNull() {
            addCriterion("least_money_to_use_bonus is null");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusIsNotNull() {
            addCriterion("least_money_to_use_bonus is not null");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusEqualTo(Integer value) {
            addCriterion("least_money_to_use_bonus =", value, "least_money_to_use_bonus");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusNotEqualTo(Integer value) {
            addCriterion("least_money_to_use_bonus <>", value, "least_money_to_use_bonus");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusGreaterThan(Integer value) {
            addCriterion("least_money_to_use_bonus >", value, "least_money_to_use_bonus");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusGreaterThanOrEqualTo(Integer value) {
            addCriterion("least_money_to_use_bonus >=", value, "least_money_to_use_bonus");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusLessThan(Integer value) {
            addCriterion("least_money_to_use_bonus <", value, "least_money_to_use_bonus");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusLessThanOrEqualTo(Integer value) {
            addCriterion("least_money_to_use_bonus <=", value, "least_money_to_use_bonus");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusIn(List<Integer> values) {
            addCriterion("least_money_to_use_bonus in", values, "least_money_to_use_bonus");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusNotIn(List<Integer> values) {
            addCriterion("least_money_to_use_bonus not in", values, "least_money_to_use_bonus");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusBetween(Integer value1, Integer value2) {
            addCriterion("least_money_to_use_bonus between", value1, value2, "least_money_to_use_bonus");
            return (Criteria) this;
        }

        public Criteria andLeast_money_to_use_bonusNotBetween(Integer value1, Integer value2) {
            addCriterion("least_money_to_use_bonus not between", value1, value2, "least_money_to_use_bonus");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIsNull() {
            addCriterion("logoUrl is null");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIsNotNull() {
            addCriterion("logoUrl is not null");
            return (Criteria) this;
        }

        public Criteria andLogoUrlEqualTo(String value) {
            addCriterion("logoUrl =", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotEqualTo(String value) {
            addCriterion("logoUrl <>", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlGreaterThan(String value) {
            addCriterion("logoUrl >", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("logoUrl >=", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLessThan(String value) {
            addCriterion("logoUrl <", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLessThanOrEqualTo(String value) {
            addCriterion("logoUrl <=", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLike(String value) {
            addCriterion("logoUrl like", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotLike(String value) {
            addCriterion("logoUrl not like", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIn(List<String> values) {
            addCriterion("logoUrl in", values, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotIn(List<String> values) {
            addCriterion("logoUrl not in", values, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlBetween(String value1, String value2) {
            addCriterion("logoUrl between", value1, value2, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotBetween(String value1, String value2) {
            addCriterion("logoUrl not between", value1, value2, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusIsNull() {
            addCriterion("max_increase_bonus is null");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusIsNotNull() {
            addCriterion("max_increase_bonus is not null");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusEqualTo(Integer value) {
            addCriterion("max_increase_bonus =", value, "max_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusNotEqualTo(Integer value) {
            addCriterion("max_increase_bonus <>", value, "max_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusGreaterThan(Integer value) {
            addCriterion("max_increase_bonus >", value, "max_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_increase_bonus >=", value, "max_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusLessThan(Integer value) {
            addCriterion("max_increase_bonus <", value, "max_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusLessThanOrEqualTo(Integer value) {
            addCriterion("max_increase_bonus <=", value, "max_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusIn(List<Integer> values) {
            addCriterion("max_increase_bonus in", values, "max_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusNotIn(List<Integer> values) {
            addCriterion("max_increase_bonus not in", values, "max_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusBetween(Integer value1, Integer value2) {
            addCriterion("max_increase_bonus between", value1, value2, "max_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_increase_bonusNotBetween(Integer value1, Integer value2) {
            addCriterion("max_increase_bonus not between", value1, value2, "max_increase_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusIsNull() {
            addCriterion("max_reduce_bonus is null");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusIsNotNull() {
            addCriterion("max_reduce_bonus is not null");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusEqualTo(Integer value) {
            addCriterion("max_reduce_bonus =", value, "max_reduce_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusNotEqualTo(Integer value) {
            addCriterion("max_reduce_bonus <>", value, "max_reduce_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusGreaterThan(Integer value) {
            addCriterion("max_reduce_bonus >", value, "max_reduce_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_reduce_bonus >=", value, "max_reduce_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusLessThan(Integer value) {
            addCriterion("max_reduce_bonus <", value, "max_reduce_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusLessThanOrEqualTo(Integer value) {
            addCriterion("max_reduce_bonus <=", value, "max_reduce_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusIn(List<Integer> values) {
            addCriterion("max_reduce_bonus in", values, "max_reduce_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusNotIn(List<Integer> values) {
            addCriterion("max_reduce_bonus not in", values, "max_reduce_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusBetween(Integer value1, Integer value2) {
            addCriterion("max_reduce_bonus between", value1, value2, "max_reduce_bonus");
            return (Criteria) this;
        }

        public Criteria andMax_reduce_bonusNotBetween(Integer value1, Integer value2) {
            addCriterion("max_reduce_bonus not between", value1, value2, "max_reduce_bonus");
            return (Criteria) this;
        }

        public Criteria andNoticeIsNull() {
            addCriterion("notice is null");
            return (Criteria) this;
        }

        public Criteria andNoticeIsNotNull() {
            addCriterion("notice is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeEqualTo(String value) {
            addCriterion("notice =", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeNotEqualTo(String value) {
            addCriterion("notice <>", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeGreaterThan(String value) {
            addCriterion("notice >", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeGreaterThanOrEqualTo(String value) {
            addCriterion("notice >=", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeLessThan(String value) {
            addCriterion("notice <", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeLessThanOrEqualTo(String value) {
            addCriterion("notice <=", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeLike(String value) {
            addCriterion("notice like", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeNotLike(String value) {
            addCriterion("notice not like", value, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeIn(List<String> values) {
            addCriterion("notice in", values, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeNotIn(List<String> values) {
            addCriterion("notice not in", values, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeBetween(String value1, String value2) {
            addCriterion("notice between", value1, value2, "notice");
            return (Criteria) this;
        }

        public Criteria andNoticeNotBetween(String value1, String value2) {
            addCriterion("notice not between", value1, value2, "notice");
            return (Criteria) this;
        }

        public Criteria andPrerogativeIsNull() {
            addCriterion("prerogative is null");
            return (Criteria) this;
        }

        public Criteria andPrerogativeIsNotNull() {
            addCriterion("prerogative is not null");
            return (Criteria) this;
        }

        public Criteria andPrerogativeEqualTo(String value) {
            addCriterion("prerogative =", value, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeNotEqualTo(String value) {
            addCriterion("prerogative <>", value, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeGreaterThan(String value) {
            addCriterion("prerogative >", value, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeGreaterThanOrEqualTo(String value) {
            addCriterion("prerogative >=", value, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeLessThan(String value) {
            addCriterion("prerogative <", value, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeLessThanOrEqualTo(String value) {
            addCriterion("prerogative <=", value, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeLike(String value) {
            addCriterion("prerogative like", value, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeNotLike(String value) {
            addCriterion("prerogative not like", value, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeIn(List<String> values) {
            addCriterion("prerogative in", values, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeNotIn(List<String> values) {
            addCriterion("prerogative not in", values, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeBetween(String value1, String value2) {
            addCriterion("prerogative between", value1, value2, "prerogative");
            return (Criteria) this;
        }

        public Criteria andPrerogativeNotBetween(String value1, String value2) {
            addCriterion("prerogative not between", value1, value2, "prerogative");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyIsNull() {
            addCriterion("reduce_money is null");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyIsNotNull() {
            addCriterion("reduce_money is not null");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyEqualTo(Integer value) {
            addCriterion("reduce_money =", value, "reduce_money");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyNotEqualTo(Integer value) {
            addCriterion("reduce_money <>", value, "reduce_money");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyGreaterThan(Integer value) {
            addCriterion("reduce_money >", value, "reduce_money");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("reduce_money >=", value, "reduce_money");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyLessThan(Integer value) {
            addCriterion("reduce_money <", value, "reduce_money");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyLessThanOrEqualTo(Integer value) {
            addCriterion("reduce_money <=", value, "reduce_money");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyIn(List<Integer> values) {
            addCriterion("reduce_money in", values, "reduce_money");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyNotIn(List<Integer> values) {
            addCriterion("reduce_money not in", values, "reduce_money");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyBetween(Integer value1, Integer value2) {
            addCriterion("reduce_money between", value1, value2, "reduce_money");
            return (Criteria) this;
        }

        public Criteria andReduce_moneyNotBetween(Integer value1, Integer value2) {
            addCriterion("reduce_money not between", value1, value2, "reduce_money");
            return (Criteria) this;
        }

        public Criteria andServicePhoneIsNull() {
            addCriterion("servicePhone is null");
            return (Criteria) this;
        }

        public Criteria andServicePhoneIsNotNull() {
            addCriterion("servicePhone is not null");
            return (Criteria) this;
        }

        public Criteria andServicePhoneEqualTo(String value) {
            addCriterion("servicePhone =", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneNotEqualTo(String value) {
            addCriterion("servicePhone <>", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneGreaterThan(String value) {
            addCriterion("servicePhone >", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("servicePhone >=", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneLessThan(String value) {
            addCriterion("servicePhone <", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneLessThanOrEqualTo(String value) {
            addCriterion("servicePhone <=", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneLike(String value) {
            addCriterion("servicePhone like", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneNotLike(String value) {
            addCriterion("servicePhone not like", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneIn(List<String> values) {
            addCriterion("servicePhone in", values, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneNotIn(List<String> values) {
            addCriterion("servicePhone not in", values, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneBetween(String value1, String value2) {
            addCriterion("servicePhone between", value1, value2, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneNotBetween(String value1, String value2) {
            addCriterion("servicePhone not between", value1, value2, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andSku_quantityIsNull() {
            addCriterion("sku_quantity is null");
            return (Criteria) this;
        }

        public Criteria andSku_quantityIsNotNull() {
            addCriterion("sku_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andSku_quantityEqualTo(Long value) {
            addCriterion("sku_quantity =", value, "sku_quantity");
            return (Criteria) this;
        }

        public Criteria andSku_quantityNotEqualTo(Long value) {
            addCriterion("sku_quantity <>", value, "sku_quantity");
            return (Criteria) this;
        }

        public Criteria andSku_quantityGreaterThan(Long value) {
            addCriterion("sku_quantity >", value, "sku_quantity");
            return (Criteria) this;
        }

        public Criteria andSku_quantityGreaterThanOrEqualTo(Long value) {
            addCriterion("sku_quantity >=", value, "sku_quantity");
            return (Criteria) this;
        }

        public Criteria andSku_quantityLessThan(Long value) {
            addCriterion("sku_quantity <", value, "sku_quantity");
            return (Criteria) this;
        }

        public Criteria andSku_quantityLessThanOrEqualTo(Long value) {
            addCriterion("sku_quantity <=", value, "sku_quantity");
            return (Criteria) this;
        }

        public Criteria andSku_quantityIn(List<Long> values) {
            addCriterion("sku_quantity in", values, "sku_quantity");
            return (Criteria) this;
        }

        public Criteria andSku_quantityNotIn(List<Long> values) {
            addCriterion("sku_quantity not in", values, "sku_quantity");
            return (Criteria) this;
        }

        public Criteria andSku_quantityBetween(Long value1, Long value2) {
            addCriterion("sku_quantity between", value1, value2, "sku_quantity");
            return (Criteria) this;
        }

        public Criteria andSku_quantityNotBetween(Long value1, Long value2) {
            addCriterion("sku_quantity not between", value1, value2, "sku_quantity");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idIsNull() {
            addCriterion("createdBy_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idIsNotNull() {
            addCriterion("createdBy_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idEqualTo(Long value) {
            addCriterion("createdBy_id =", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idNotEqualTo(Long value) {
            addCriterion("createdBy_id <>", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idGreaterThan(Long value) {
            addCriterion("createdBy_id >", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idGreaterThanOrEqualTo(Long value) {
            addCriterion("createdBy_id >=", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idLessThan(Long value) {
            addCriterion("createdBy_id <", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idLessThanOrEqualTo(Long value) {
            addCriterion("createdBy_id <=", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idIn(List<Long> values) {
            addCriterion("createdBy_id in", values, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idNotIn(List<Long> values) {
            addCriterion("createdBy_id not in", values, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idBetween(Long value1, Long value2) {
            addCriterion("createdBy_id between", value1, value2, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idNotBetween(Long value1, Long value2) {
            addCriterion("createdBy_id not between", value1, value2, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idIsNull() {
            addCriterion("lastModifiedBy_id is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idIsNotNull() {
            addCriterion("lastModifiedBy_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idEqualTo(Long value) {
            addCriterion("lastModifiedBy_id =", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idNotEqualTo(Long value) {
            addCriterion("lastModifiedBy_id <>", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idGreaterThan(Long value) {
            addCriterion("lastModifiedBy_id >", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idGreaterThanOrEqualTo(Long value) {
            addCriterion("lastModifiedBy_id >=", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idLessThan(Long value) {
            addCriterion("lastModifiedBy_id <", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idLessThanOrEqualTo(Long value) {
            addCriterion("lastModifiedBy_id <=", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idIn(List<Long> values) {
            addCriterion("lastModifiedBy_id in", values, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idNotIn(List<Long> values) {
            addCriterion("lastModifiedBy_id not in", values, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idBetween(Long value1, Long value2) {
            addCriterion("lastModifiedBy_id between", value1, value2, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idNotBetween(Long value1, Long value2) {
            addCriterion("lastModifiedBy_id not between", value1, value2, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idIsNull() {
            addCriterion("card_coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idIsNotNull() {
            addCriterion("card_coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idEqualTo(Long value) {
            addCriterion("card_coupon_id =", value, "card_coupon_id");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idNotEqualTo(Long value) {
            addCriterion("card_coupon_id <>", value, "card_coupon_id");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idGreaterThan(Long value) {
            addCriterion("card_coupon_id >", value, "card_coupon_id");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idGreaterThanOrEqualTo(Long value) {
            addCriterion("card_coupon_id >=", value, "card_coupon_id");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idLessThan(Long value) {
            addCriterion("card_coupon_id <", value, "card_coupon_id");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idLessThanOrEqualTo(Long value) {
            addCriterion("card_coupon_id <=", value, "card_coupon_id");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idIn(List<Long> values) {
            addCriterion("card_coupon_id in", values, "card_coupon_id");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idNotIn(List<Long> values) {
            addCriterion("card_coupon_id not in", values, "card_coupon_id");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idBetween(Long value1, Long value2) {
            addCriterion("card_coupon_id between", value1, value2, "card_coupon_id");
            return (Criteria) this;
        }

        public Criteria andCard_coupon_idNotBetween(Long value1, Long value2) {
            addCriterion("card_coupon_id not between", value1, value2, "card_coupon_id");
            return (Criteria) this;
        }

        public Criteria andActivateUrlIsNull() {
            addCriterion("activateUrl is null");
            return (Criteria) this;
        }

        public Criteria andActivateUrlIsNotNull() {
            addCriterion("activateUrl is not null");
            return (Criteria) this;
        }

        public Criteria andActivateUrlEqualTo(String value) {
            addCriterion("activateUrl =", value, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlNotEqualTo(String value) {
            addCriterion("activateUrl <>", value, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlGreaterThan(String value) {
            addCriterion("activateUrl >", value, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlGreaterThanOrEqualTo(String value) {
            addCriterion("activateUrl >=", value, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlLessThan(String value) {
            addCriterion("activateUrl <", value, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlLessThanOrEqualTo(String value) {
            addCriterion("activateUrl <=", value, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlLike(String value) {
            addCriterion("activateUrl like", value, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlNotLike(String value) {
            addCriterion("activateUrl not like", value, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlIn(List<String> values) {
            addCriterion("activateUrl in", values, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlNotIn(List<String> values) {
            addCriterion("activateUrl not in", values, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlBetween(String value1, String value2) {
            addCriterion("activateUrl between", value1, value2, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andActivateUrlNotBetween(String value1, String value2) {
            addCriterion("activateUrl not between", value1, value2, "activateUrl");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityIsNull() {
            addCriterion("sku_surplusQuantity is null");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityIsNotNull() {
            addCriterion("sku_surplusQuantity is not null");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityEqualTo(Long value) {
            addCriterion("sku_surplusQuantity =", value, "sku_surplusQuantity");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityNotEqualTo(Long value) {
            addCriterion("sku_surplusQuantity <>", value, "sku_surplusQuantity");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityGreaterThan(Long value) {
            addCriterion("sku_surplusQuantity >", value, "sku_surplusQuantity");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityGreaterThanOrEqualTo(Long value) {
            addCriterion("sku_surplusQuantity >=", value, "sku_surplusQuantity");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityLessThan(Long value) {
            addCriterion("sku_surplusQuantity <", value, "sku_surplusQuantity");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityLessThanOrEqualTo(Long value) {
            addCriterion("sku_surplusQuantity <=", value, "sku_surplusQuantity");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityIn(List<Long> values) {
            addCriterion("sku_surplusQuantity in", values, "sku_surplusQuantity");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityNotIn(List<Long> values) {
            addCriterion("sku_surplusQuantity not in", values, "sku_surplusQuantity");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityBetween(Long value1, Long value2) {
            addCriterion("sku_surplusQuantity between", value1, value2, "sku_surplusQuantity");
            return (Criteria) this;
        }

        public Criteria andSku_surplusQuantityNotBetween(Long value1, Long value2) {
            addCriterion("sku_surplusQuantity not between", value1, value2, "sku_surplusQuantity");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andActivate_urlIsNull() {
            addCriterion("activate_url is null");
            return (Criteria) this;
        }

        public Criteria andActivate_urlIsNotNull() {
            addCriterion("activate_url is not null");
            return (Criteria) this;
        }

        public Criteria andActivate_urlEqualTo(String value) {
            addCriterion("activate_url =", value, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlNotEqualTo(String value) {
            addCriterion("activate_url <>", value, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlGreaterThan(String value) {
            addCriterion("activate_url >", value, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlGreaterThanOrEqualTo(String value) {
            addCriterion("activate_url >=", value, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlLessThan(String value) {
            addCriterion("activate_url <", value, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlLessThanOrEqualTo(String value) {
            addCriterion("activate_url <=", value, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlLike(String value) {
            addCriterion("activate_url like", value, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlNotLike(String value) {
            addCriterion("activate_url not like", value, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlIn(List<String> values) {
            addCriterion("activate_url in", values, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlNotIn(List<String> values) {
            addCriterion("activate_url not in", values, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlBetween(String value1, String value2) {
            addCriterion("activate_url between", value1, value2, "activate_url");
            return (Criteria) this;
        }

        public Criteria andActivate_urlNotBetween(String value1, String value2) {
            addCriterion("activate_url not between", value1, value2, "activate_url");
            return (Criteria) this;
        }

        public Criteria andCard_idIsNull() {
            addCriterion("card_id is null");
            return (Criteria) this;
        }

        public Criteria andCard_idIsNotNull() {
            addCriterion("card_id is not null");
            return (Criteria) this;
        }

        public Criteria andCard_idEqualTo(String value) {
            addCriterion("card_id =", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idNotEqualTo(String value) {
            addCriterion("card_id <>", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idGreaterThan(String value) {
            addCriterion("card_id >", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idGreaterThanOrEqualTo(String value) {
            addCriterion("card_id >=", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idLessThan(String value) {
            addCriterion("card_id <", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idLessThanOrEqualTo(String value) {
            addCriterion("card_id <=", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idLike(String value) {
            addCriterion("card_id like", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idNotLike(String value) {
            addCriterion("card_id not like", value, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idIn(List<String> values) {
            addCriterion("card_id in", values, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idNotIn(List<String> values) {
            addCriterion("card_id not in", values, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idBetween(String value1, String value2) {
            addCriterion("card_id between", value1, value2, "card_id");
            return (Criteria) this;
        }

        public Criteria andCard_idNotBetween(String value1, String value2) {
            addCriterion("card_id not between", value1, value2, "card_id");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlIsNull() {
            addCriterion("wxbackgroudUrl is null");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlIsNotNull() {
            addCriterion("wxbackgroudUrl is not null");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlEqualTo(String value) {
            addCriterion("wxbackgroudUrl =", value, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlNotEqualTo(String value) {
            addCriterion("wxbackgroudUrl <>", value, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlGreaterThan(String value) {
            addCriterion("wxbackgroudUrl >", value, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlGreaterThanOrEqualTo(String value) {
            addCriterion("wxbackgroudUrl >=", value, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlLessThan(String value) {
            addCriterion("wxbackgroudUrl <", value, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlLessThanOrEqualTo(String value) {
            addCriterion("wxbackgroudUrl <=", value, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlLike(String value) {
            addCriterion("wxbackgroudUrl like", value, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlNotLike(String value) {
            addCriterion("wxbackgroudUrl not like", value, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlIn(List<String> values) {
            addCriterion("wxbackgroudUrl in", values, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlNotIn(List<String> values) {
            addCriterion("wxbackgroudUrl not in", values, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlBetween(String value1, String value2) {
            addCriterion("wxbackgroudUrl between", value1, value2, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxbackgroudUrlNotBetween(String value1, String value2) {
            addCriterion("wxbackgroudUrl not between", value1, value2, "wxbackgroudUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlIsNull() {
            addCriterion("wxlogoUrl is null");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlIsNotNull() {
            addCriterion("wxlogoUrl is not null");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlEqualTo(String value) {
            addCriterion("wxlogoUrl =", value, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlNotEqualTo(String value) {
            addCriterion("wxlogoUrl <>", value, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlGreaterThan(String value) {
            addCriterion("wxlogoUrl >", value, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("wxlogoUrl >=", value, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlLessThan(String value) {
            addCriterion("wxlogoUrl <", value, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlLessThanOrEqualTo(String value) {
            addCriterion("wxlogoUrl <=", value, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlLike(String value) {
            addCriterion("wxlogoUrl like", value, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlNotLike(String value) {
            addCriterion("wxlogoUrl not like", value, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlIn(List<String> values) {
            addCriterion("wxlogoUrl in", values, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlNotIn(List<String> values) {
            addCriterion("wxlogoUrl not in", values, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlBetween(String value1, String value2) {
            addCriterion("wxlogoUrl between", value1, value2, "wxlogoUrl");
            return (Criteria) this;
        }

        public Criteria andWxlogoUrlNotBetween(String value1, String value2) {
            addCriterion("wxlogoUrl not between", value1, value2, "wxlogoUrl");
            return (Criteria) this;
        }
    }

    /**
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}