package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.AppPhoto;
import com.airlenet.play.website.model.AppPhotoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AppPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_photo
     *
     * @date
     */
    long countByExample(AppPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_photo
     *
     * @date
     */
    int deleteByExample(AppPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_photo
     *
     * @date
     */
    int insert(AppPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_photo
     *
     * @date
     */
    int insertSelective(AppPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_photo
     *
     * @date
     */
    List<AppPhoto> selectByExample(AppPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_photo
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") AppPhoto record, @Param("example") AppPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_photo
     *
     * @date
     */
    int updateByExample(@Param("record") AppPhoto record, @Param("example") AppPhotoExample example);
}