package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.PluginConfigAttribute;
import com.airlenet.play.website.model.PluginConfigAttributeExample;
import com.airlenet.play.website.model.PluginConfigAttributeKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PluginConfigAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    long countByExample(PluginConfigAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    int deleteByExample(PluginConfigAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    int deleteByPrimaryKey(PluginConfigAttributeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    int insert(PluginConfigAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    int insertSelective(PluginConfigAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    List<PluginConfigAttribute> selectByExample(PluginConfigAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    PluginConfigAttribute selectByPrimaryKey(PluginConfigAttributeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") PluginConfigAttribute record, @Param("example") PluginConfigAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    int updateByExample(@Param("record") PluginConfigAttribute record, @Param("example") PluginConfigAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    int updateByPrimaryKeySelective(PluginConfigAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_config_attribute
     *
     * @date
     */
    int updateByPrimaryKey(PluginConfigAttribute record);
}