package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.PluginOauthUserExample;
import com.airlenet.play.website.model.PluginOauthUser;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PluginOauthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    long countByExample(PluginOauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    int deleteByExample(PluginOauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    int insert(PluginOauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    int insertSelective(PluginOauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    List<PluginOauthUser> selectByExample(PluginOauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    PluginOauthUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") PluginOauthUser record, @Param("example") PluginOauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    int updateByExample(@Param("record") PluginOauthUser record, @Param("example") PluginOauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    int updateByPrimaryKeySelective(PluginOauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_oauth_user
     *
     * @date
     */
    int updateByPrimaryKey(PluginOauthUser record);
}