package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.SysArea;
import com.airlenet.play.website.model.SysAreaExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SysAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    long countByExample(SysAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    int deleteByExample(SysAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    int insert(SysArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    int insertSelective(SysArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    List<SysArea> selectByExample(SysAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    SysArea selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") SysArea record, @Param("example") SysAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    int updateByExample(@Param("record") SysArea record, @Param("example") SysAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    int updateByPrimaryKeySelective(SysArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @date
     */
    int updateByPrimaryKey(SysArea record);
}