package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.SysAuthority;
import com.airlenet.play.website.model.SysAuthorityExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SysAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    long countByExample(SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    int deleteByExample(SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    int insert(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    int insertSelective(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    List<SysAuthority> selectByExample(SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    SysAuthority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") SysAuthority record, @Param("example") SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    int updateByExample(@Param("record") SysAuthority record, @Param("example") SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    int updateByPrimaryKeySelective(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @date
     */
    int updateByPrimaryKey(SysAuthority record);
}