package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.SysRoleAuthorityExample;
import com.airlenet.play.website.model.SysRoleAuthority;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SysRoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @date
     */
    long countByExample(SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @date
     */
    int deleteByExample(SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @date
     */
    int insert(SysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @date
     */
    int insertSelective(SysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @date
     */
    List<SysRoleAuthority> selectByExample(SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") SysRoleAuthority record, @Param("example") SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @date
     */
    int updateByExample(@Param("record") SysRoleAuthority record, @Param("example") SysRoleAuthorityExample example);
}