package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.SysUserToRoleExample;
import com.airlenet.play.website.model.SysUserToRoleKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SysUserToRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_to_role
     *
     * @date
     */
    long countByExample(SysUserToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_to_role
     *
     * @date
     */
    int deleteByExample(SysUserToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_to_role
     *
     * @date
     */
    int deleteByPrimaryKey(SysUserToRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_to_role
     *
     * @date
     */
    int insert(SysUserToRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_to_role
     *
     * @date
     */
    int insertSelective(SysUserToRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_to_role
     *
     * @date
     */
    List<SysUserToRoleKey> selectByExample(SysUserToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_to_role
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") SysUserToRoleKey record, @Param("example") SysUserToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_to_role
     *
     * @date
     */
    int updateByExample(@Param("record") SysUserToRoleKey record, @Param("example") SysUserToRoleExample example);
}