package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.TblPluginConfigExample;
import com.airlenet.play.website.model.TblPluginConfig;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TblPluginConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    long countByExample(TblPluginConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    int deleteByExample(TblPluginConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    int insert(TblPluginConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    int insertSelective(TblPluginConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    List<TblPluginConfig> selectByExample(TblPluginConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    TblPluginConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") TblPluginConfig record, @Param("example") TblPluginConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    int updateByExample(@Param("record") TblPluginConfig record, @Param("example") TblPluginConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    int updateByPrimaryKeySelective(TblPluginConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config
     *
     * @date
     */
    int updateByPrimaryKey(TblPluginConfig record);
}