package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.WechatCardCouponMember;
import com.airlenet.play.website.model.WechatCardCouponMemberExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface WechatCardCouponMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    long countByExample(WechatCardCouponMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    int deleteByExample(WechatCardCouponMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    int insert(WechatCardCouponMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    int insertSelective(WechatCardCouponMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    List<WechatCardCouponMember> selectByExample(WechatCardCouponMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    WechatCardCouponMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") WechatCardCouponMember record, @Param("example") WechatCardCouponMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    int updateByExample(@Param("record") WechatCardCouponMember record, @Param("example") WechatCardCouponMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    int updateByPrimaryKeySelective(WechatCardCouponMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon_member
     *
     * @date
     */
    int updateByPrimaryKey(WechatCardCouponMember record);
}