package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.WechatImgtextTemplateWechatImgtextItemKey;
import com.airlenet.play.website.model.WechatImgtextTemplateWechatImgtextItemExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface WechatImgtextTemplateWechatImgtextItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    long countByExample(WechatImgtextTemplateWechatImgtextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    int deleteByExample(WechatImgtextTemplateWechatImgtextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    int deleteByPrimaryKey(WechatImgtextTemplateWechatImgtextItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    int insert(WechatImgtextTemplateWechatImgtextItemKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    int insertSelective(WechatImgtextTemplateWechatImgtextItemKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    List<WechatImgtextTemplateWechatImgtextItemKey> selectByExample(WechatImgtextTemplateWechatImgtextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") WechatImgtextTemplateWechatImgtextItemKey record, @Param("example") WechatImgtextTemplateWechatImgtextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    int updateByExample(@Param("record") WechatImgtextTemplateWechatImgtextItemKey record, @Param("example") WechatImgtextTemplateWechatImgtextItemExample example);
}