package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.WechatMaterial;
import com.airlenet.play.website.model.WechatMaterialExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface WechatMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    long countByExample(WechatMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    int deleteByExample(WechatMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    int insert(WechatMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    int insertSelective(WechatMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    List<WechatMaterial> selectByExample(WechatMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    WechatMaterial selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") WechatMaterial record, @Param("example") WechatMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    int updateByExample(@Param("record") WechatMaterial record, @Param("example") WechatMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    int updateByPrimaryKeySelective(WechatMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_material
     *
     * @date
     */
    int updateByPrimaryKey(WechatMaterial record);
}