package com.airlenet.play.website.model;

import java.io.Serializable;

/**
 * database table shop_product_category_to_brand
 *
 * @date do_not_delete_during_merge
 */
public class ShopProductCategoryToBrandKey implements Serializable {
    private Long productCategories_id;

    private Long brands_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_product_category_to_brand
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getProductCategories_id() {
        return productCategories_id;
    }

    public void setProductCategories_id(Long productCategories_id) {
        this.productCategories_id = productCategories_id;
    }

    public Long getBrands_id() {
        return brands_id;
    }

    public void setBrands_id(Long brands_id) {
        this.brands_id = brands_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_category_to_brand
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShopProductCategoryToBrandKey other = (ShopProductCategoryToBrandKey) that;
        return (this.getProductCategories_id() == null ? other.getProductCategories_id() == null : this.getProductCategories_id().equals(other.getProductCategories_id()))
                && (this.getBrands_id() == null ? other.getBrands_id() == null : this.getBrands_id().equals(other.getBrands_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_category_to_brand
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProductCategories_id() == null) ? 0 : getProductCategories_id().hashCode());
        result = prime * result + ((getBrands_id() == null) ? 0 : getBrands_id().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_category_to_brand
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productCategories_id=").append(productCategories_id);
        sb.append(", brands_id=").append(brands_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}