package com.airlenet.play.website.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysSettingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_setting
     *
     * @date
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_setting
     *
     * @date
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_setting
     *
     * @date
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    public SysSettingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @date
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     *
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("createdDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("createdDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("createdDate =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("createdDate <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("createdDate >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdDate >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("createdDate <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("createdDate <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("createdDate in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("createdDate not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("createdDate between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("createdDate not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("lastModifiedDate is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("lastModifiedDate is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(Date value) {
            addCriterion("lastModifiedDate =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(Date value) {
            addCriterion("lastModifiedDate <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(Date value) {
            addCriterion("lastModifiedDate >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("lastModifiedDate >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(Date value) {
            addCriterion("lastModifiedDate <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("lastModifiedDate <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<Date> values) {
            addCriterion("lastModifiedDate in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<Date> values) {
            addCriterion("lastModifiedDate not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
            addCriterion("lastModifiedDate between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("lastModifiedDate not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerIsNull() {
            addCriterion("adminLoginBanner is null");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerIsNotNull() {
            addCriterion("adminLoginBanner is not null");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerEqualTo(String value) {
            addCriterion("adminLoginBanner =", value, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerNotEqualTo(String value) {
            addCriterion("adminLoginBanner <>", value, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerGreaterThan(String value) {
            addCriterion("adminLoginBanner >", value, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerGreaterThanOrEqualTo(String value) {
            addCriterion("adminLoginBanner >=", value, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerLessThan(String value) {
            addCriterion("adminLoginBanner <", value, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerLessThanOrEqualTo(String value) {
            addCriterion("adminLoginBanner <=", value, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerLike(String value) {
            addCriterion("adminLoginBanner like", value, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerNotLike(String value) {
            addCriterion("adminLoginBanner not like", value, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerIn(List<String> values) {
            addCriterion("adminLoginBanner in", values, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerNotIn(List<String> values) {
            addCriterion("adminLoginBanner not in", values, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerBetween(String value1, String value2) {
            addCriterion("adminLoginBanner between", value1, value2, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andAdminLoginBannerNotBetween(String value1, String value2) {
            addCriterion("adminLoginBanner not between", value1, value2, "adminLoginBanner");
            return (Criteria) this;
        }

        public Criteria andCerttextIsNull() {
            addCriterion("certtext is null");
            return (Criteria) this;
        }

        public Criteria andCerttextIsNotNull() {
            addCriterion("certtext is not null");
            return (Criteria) this;
        }

        public Criteria andCerttextEqualTo(String value) {
            addCriterion("certtext =", value, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextNotEqualTo(String value) {
            addCriterion("certtext <>", value, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextGreaterThan(String value) {
            addCriterion("certtext >", value, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextGreaterThanOrEqualTo(String value) {
            addCriterion("certtext >=", value, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextLessThan(String value) {
            addCriterion("certtext <", value, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextLessThanOrEqualTo(String value) {
            addCriterion("certtext <=", value, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextLike(String value) {
            addCriterion("certtext like", value, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextNotLike(String value) {
            addCriterion("certtext not like", value, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextIn(List<String> values) {
            addCriterion("certtext in", values, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextNotIn(List<String> values) {
            addCriterion("certtext not in", values, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextBetween(String value1, String value2) {
            addCriterion("certtext between", value1, value2, "certtext");
            return (Criteria) this;
        }

        public Criteria andCerttextNotBetween(String value1, String value2) {
            addCriterion("certtext not between", value1, value2, "certtext");
            return (Criteria) this;
        }

        public Criteria andContactIsNull() {
            addCriterion("contact is null");
            return (Criteria) this;
        }

        public Criteria andContactIsNotNull() {
            addCriterion("contact is not null");
            return (Criteria) this;
        }

        public Criteria andContactEqualTo(String value) {
            addCriterion("contact =", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotEqualTo(String value) {
            addCriterion("contact <>", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactGreaterThan(String value) {
            addCriterion("contact >", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactGreaterThanOrEqualTo(String value) {
            addCriterion("contact >=", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLessThan(String value) {
            addCriterion("contact <", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLessThanOrEqualTo(String value) {
            addCriterion("contact <=", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLike(String value) {
            addCriterion("contact like", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotLike(String value) {
            addCriterion("contact not like", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactIn(List<String> values) {
            addCriterion("contact in", values, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotIn(List<String> values) {
            addCriterion("contact not in", values, "contact");
            return (Criteria) this;
        }

        public Criteria andContactBetween(String value1, String value2) {
            addCriterion("contact between", value1, value2, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotBetween(String value1, String value2) {
            addCriterion("contact not between", value1, value2, "contact");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andHotSearchIsNull() {
            addCriterion("hotSearch is null");
            return (Criteria) this;
        }

        public Criteria andHotSearchIsNotNull() {
            addCriterion("hotSearch is not null");
            return (Criteria) this;
        }

        public Criteria andHotSearchEqualTo(String value) {
            addCriterion("hotSearch =", value, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchNotEqualTo(String value) {
            addCriterion("hotSearch <>", value, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchGreaterThan(String value) {
            addCriterion("hotSearch >", value, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchGreaterThanOrEqualTo(String value) {
            addCriterion("hotSearch >=", value, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchLessThan(String value) {
            addCriterion("hotSearch <", value, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchLessThanOrEqualTo(String value) {
            addCriterion("hotSearch <=", value, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchLike(String value) {
            addCriterion("hotSearch like", value, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchNotLike(String value) {
            addCriterion("hotSearch not like", value, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchIn(List<String> values) {
            addCriterion("hotSearch in", values, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchNotIn(List<String> values) {
            addCriterion("hotSearch not in", values, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchBetween(String value1, String value2) {
            addCriterion("hotSearch between", value1, value2, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andHotSearchNotBetween(String value1, String value2) {
            addCriterion("hotSearch not between", value1, value2, "hotSearch");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledIsNull() {
            addCriterion("isSiteEnabled is null");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledIsNotNull() {
            addCriterion("isSiteEnabled is not null");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledEqualTo(Boolean value) {
            addCriterion("isSiteEnabled =", value, "isSiteEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledNotEqualTo(Boolean value) {
            addCriterion("isSiteEnabled <>", value, "isSiteEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledGreaterThan(Boolean value) {
            addCriterion("isSiteEnabled >", value, "isSiteEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isSiteEnabled >=", value, "isSiteEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledLessThan(Boolean value) {
            addCriterion("isSiteEnabled <", value, "isSiteEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("isSiteEnabled <=", value, "isSiteEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledIn(List<Boolean> values) {
            addCriterion("isSiteEnabled in", values, "isSiteEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledNotIn(List<Boolean> values) {
            addCriterion("isSiteEnabled not in", values, "isSiteEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("isSiteEnabled between", value1, value2, "isSiteEnabled");
            return (Criteria) this;
        }

        public Criteria andIsSiteEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isSiteEnabled not between", value1, value2, "isSiteEnabled");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("logo is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("logo is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("logo =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("logo <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("logo >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("logo >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("logo <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("logo <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("logo like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("logo not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("logo in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("logo not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("logo between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("logo not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andPhone1IsNull() {
            addCriterion("phone1 is null");
            return (Criteria) this;
        }

        public Criteria andPhone1IsNotNull() {
            addCriterion("phone1 is not null");
            return (Criteria) this;
        }

        public Criteria andPhone1EqualTo(String value) {
            addCriterion("phone1 =", value, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1NotEqualTo(String value) {
            addCriterion("phone1 <>", value, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1GreaterThan(String value) {
            addCriterion("phone1 >", value, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1GreaterThanOrEqualTo(String value) {
            addCriterion("phone1 >=", value, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1LessThan(String value) {
            addCriterion("phone1 <", value, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1LessThanOrEqualTo(String value) {
            addCriterion("phone1 <=", value, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1Like(String value) {
            addCriterion("phone1 like", value, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1NotLike(String value) {
            addCriterion("phone1 not like", value, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1In(List<String> values) {
            addCriterion("phone1 in", values, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1NotIn(List<String> values) {
            addCriterion("phone1 not in", values, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1Between(String value1, String value2) {
            addCriterion("phone1 between", value1, value2, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone1NotBetween(String value1, String value2) {
            addCriterion("phone1 not between", value1, value2, "phone1");
            return (Criteria) this;
        }

        public Criteria andPhone2IsNull() {
            addCriterion("phone2 is null");
            return (Criteria) this;
        }

        public Criteria andPhone2IsNotNull() {
            addCriterion("phone2 is not null");
            return (Criteria) this;
        }

        public Criteria andPhone2EqualTo(String value) {
            addCriterion("phone2 =", value, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2NotEqualTo(String value) {
            addCriterion("phone2 <>", value, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2GreaterThan(String value) {
            addCriterion("phone2 >", value, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2GreaterThanOrEqualTo(String value) {
            addCriterion("phone2 >=", value, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2LessThan(String value) {
            addCriterion("phone2 <", value, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2LessThanOrEqualTo(String value) {
            addCriterion("phone2 <=", value, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2Like(String value) {
            addCriterion("phone2 like", value, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2NotLike(String value) {
            addCriterion("phone2 not like", value, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2In(List<String> values) {
            addCriterion("phone2 in", values, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2NotIn(List<String> values) {
            addCriterion("phone2 not in", values, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2Between(String value1, String value2) {
            addCriterion("phone2 between", value1, value2, "phone2");
            return (Criteria) this;
        }

        public Criteria andPhone2NotBetween(String value1, String value2) {
            addCriterion("phone2 not between", value1, value2, "phone2");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameIsNull() {
            addCriterion("shortSiteName is null");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameIsNotNull() {
            addCriterion("shortSiteName is not null");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameEqualTo(String value) {
            addCriterion("shortSiteName =", value, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameNotEqualTo(String value) {
            addCriterion("shortSiteName <>", value, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameGreaterThan(String value) {
            addCriterion("shortSiteName >", value, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameGreaterThanOrEqualTo(String value) {
            addCriterion("shortSiteName >=", value, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameLessThan(String value) {
            addCriterion("shortSiteName <", value, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameLessThanOrEqualTo(String value) {
            addCriterion("shortSiteName <=", value, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameLike(String value) {
            addCriterion("shortSiteName like", value, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameNotLike(String value) {
            addCriterion("shortSiteName not like", value, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameIn(List<String> values) {
            addCriterion("shortSiteName in", values, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameNotIn(List<String> values) {
            addCriterion("shortSiteName not in", values, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameBetween(String value1, String value2) {
            addCriterion("shortSiteName between", value1, value2, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andShortSiteNameNotBetween(String value1, String value2) {
            addCriterion("shortSiteName not between", value1, value2, "shortSiteName");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageIsNull() {
            addCriterion("siteCloseMessage is null");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageIsNotNull() {
            addCriterion("siteCloseMessage is not null");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageEqualTo(String value) {
            addCriterion("siteCloseMessage =", value, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageNotEqualTo(String value) {
            addCriterion("siteCloseMessage <>", value, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageGreaterThan(String value) {
            addCriterion("siteCloseMessage >", value, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageGreaterThanOrEqualTo(String value) {
            addCriterion("siteCloseMessage >=", value, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageLessThan(String value) {
            addCriterion("siteCloseMessage <", value, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageLessThanOrEqualTo(String value) {
            addCriterion("siteCloseMessage <=", value, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageLike(String value) {
            addCriterion("siteCloseMessage like", value, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageNotLike(String value) {
            addCriterion("siteCloseMessage not like", value, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageIn(List<String> values) {
            addCriterion("siteCloseMessage in", values, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageNotIn(List<String> values) {
            addCriterion("siteCloseMessage not in", values, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageBetween(String value1, String value2) {
            addCriterion("siteCloseMessage between", value1, value2, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteCloseMessageNotBetween(String value1, String value2) {
            addCriterion("siteCloseMessage not between", value1, value2, "siteCloseMessage");
            return (Criteria) this;
        }

        public Criteria andSiteNameIsNull() {
            addCriterion("siteName is null");
            return (Criteria) this;
        }

        public Criteria andSiteNameIsNotNull() {
            addCriterion("siteName is not null");
            return (Criteria) this;
        }

        public Criteria andSiteNameEqualTo(String value) {
            addCriterion("siteName =", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotEqualTo(String value) {
            addCriterion("siteName <>", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameGreaterThan(String value) {
            addCriterion("siteName >", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameGreaterThanOrEqualTo(String value) {
            addCriterion("siteName >=", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameLessThan(String value) {
            addCriterion("siteName <", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameLessThanOrEqualTo(String value) {
            addCriterion("siteName <=", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameLike(String value) {
            addCriterion("siteName like", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotLike(String value) {
            addCriterion("siteName not like", value, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameIn(List<String> values) {
            addCriterion("siteName in", values, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotIn(List<String> values) {
            addCriterion("siteName not in", values, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameBetween(String value1, String value2) {
            addCriterion("siteName between", value1, value2, "siteName");
            return (Criteria) this;
        }

        public Criteria andSiteNameNotBetween(String value1, String value2) {
            addCriterion("siteName not between", value1, value2, "siteName");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNull() {
            addCriterion("zipCode is null");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNotNull() {
            addCriterion("zipCode is not null");
            return (Criteria) this;
        }

        public Criteria andZipCodeEqualTo(String value) {
            addCriterion("zipCode =", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotEqualTo(String value) {
            addCriterion("zipCode <>", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThan(String value) {
            addCriterion("zipCode >", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("zipCode >=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThan(String value) {
            addCriterion("zipCode <", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThanOrEqualTo(String value) {
            addCriterion("zipCode <=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLike(String value) {
            addCriterion("zipCode like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotLike(String value) {
            addCriterion("zipCode not like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeIn(List<String> values) {
            addCriterion("zipCode in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotIn(List<String> values) {
            addCriterion("zipCode not in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeBetween(String value1, String value2) {
            addCriterion("zipCode between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotBetween(String value1, String value2) {
            addCriterion("zipCode not between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idIsNull() {
            addCriterion("createdBy_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idIsNotNull() {
            addCriterion("createdBy_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idEqualTo(Long value) {
            addCriterion("createdBy_id =", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idNotEqualTo(Long value) {
            addCriterion("createdBy_id <>", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idGreaterThan(Long value) {
            addCriterion("createdBy_id >", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idGreaterThanOrEqualTo(Long value) {
            addCriterion("createdBy_id >=", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idLessThan(Long value) {
            addCriterion("createdBy_id <", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idLessThanOrEqualTo(Long value) {
            addCriterion("createdBy_id <=", value, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idIn(List<Long> values) {
            addCriterion("createdBy_id in", values, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idNotIn(List<Long> values) {
            addCriterion("createdBy_id not in", values, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idBetween(Long value1, Long value2) {
            addCriterion("createdBy_id between", value1, value2, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andCreatedBy_idNotBetween(Long value1, Long value2) {
            addCriterion("createdBy_id not between", value1, value2, "createdBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idIsNull() {
            addCriterion("lastModifiedBy_id is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idIsNotNull() {
            addCriterion("lastModifiedBy_id is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idEqualTo(Long value) {
            addCriterion("lastModifiedBy_id =", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idNotEqualTo(Long value) {
            addCriterion("lastModifiedBy_id <>", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idGreaterThan(Long value) {
            addCriterion("lastModifiedBy_id >", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idGreaterThanOrEqualTo(Long value) {
            addCriterion("lastModifiedBy_id >=", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idLessThan(Long value) {
            addCriterion("lastModifiedBy_id <", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idLessThanOrEqualTo(Long value) {
            addCriterion("lastModifiedBy_id <=", value, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idIn(List<Long> values) {
            addCriterion("lastModifiedBy_id in", values, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idNotIn(List<Long> values) {
            addCriterion("lastModifiedBy_id not in", values, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idBetween(Long value1, Long value2) {
            addCriterion("lastModifiedBy_id between", value1, value2, "lastModifiedBy_id");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBy_idNotBetween(Long value1, Long value2) {
            addCriterion("lastModifiedBy_id not between", value1, value2, "lastModifiedBy_id");
            return (Criteria) this;
        }
    }

    /**
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}