package com.airlenet.play.website.model;

import java.io.Serializable;

/**
 * database table wechat_imgtext_template_wechat_imgtext_item
 *
 * @date do_not_delete_during_merge
 */
public class WechatImgtextTemplateWechatImgtextItemKey implements Serializable {
    private Long imageTextTemplateEntity_id;

    private Long items_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    private static final long serialVersionUID = 1L;

    public Long getImageTextTemplateEntity_id() {
        return imageTextTemplateEntity_id;
    }

    public void setImageTextTemplateEntity_id(Long imageTextTemplateEntity_id) {
        this.imageTextTemplateEntity_id = imageTextTemplateEntity_id;
    }

    public Long getItems_id() {
        return items_id;
    }

    public void setItems_id(Long items_id) {
        this.items_id = items_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WechatImgtextTemplateWechatImgtextItemKey other = (WechatImgtextTemplateWechatImgtextItemKey) that;
        return (this.getImageTextTemplateEntity_id() == null ? other.getImageTextTemplateEntity_id() == null : this.getImageTextTemplateEntity_id().equals(other.getImageTextTemplateEntity_id()))
                && (this.getItems_id() == null ? other.getItems_id() == null : this.getItems_id().equals(other.getItems_id()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getImageTextTemplateEntity_id() == null) ? 0 : getImageTextTemplateEntity_id().hashCode());
        result = prime * result + ((getItems_id() == null) ? 0 : getItems_id().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template_wechat_imgtext_item
     *
     * @date
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", imageTextTemplateEntity_id=").append(imageTextTemplateEntity_id);
        sb.append(", items_id=").append(items_id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}