package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.CmsSubscribe;
import com.airlenet.play.website.model.CmsSubscribeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CmsSubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    long countByExample(CmsSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    int deleteByExample(CmsSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    int insert(CmsSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    int insertSelective(CmsSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    List<CmsSubscribe> selectByExample(CmsSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    CmsSubscribe selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") CmsSubscribe record, @Param("example") CmsSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    int updateByExample(@Param("record") CmsSubscribe record, @Param("example") CmsSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    int updateByPrimaryKeySelective(CmsSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_subscribe
     *
     * @date
     */
    int updateByPrimaryKey(CmsSubscribe record);
}