package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.ShopProductToTagExample;
import com.airlenet.play.website.model.ShopProductToTagKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ShopProductToTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    long countByExample(ShopProductToTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    int deleteByExample(ShopProductToTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    int deleteByPrimaryKey(ShopProductToTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    int insert(ShopProductToTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    int insertSelective(ShopProductToTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    List<ShopProductToTagKey> selectByExample(ShopProductToTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") ShopProductToTagKey record, @Param("example") ShopProductToTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_to_tag
     *
     * @date
     */
    int updateByExample(@Param("record") ShopProductToTagKey record, @Param("example") ShopProductToTagExample example);
}