package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.SysUserCredentials;
import com.airlenet.play.website.model.SysUserCredentialsExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SysUserCredentialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    long countByExample(SysUserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    int deleteByExample(SysUserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    int insert(SysUserCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    int insertSelective(SysUserCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    List<SysUserCredentials> selectByExample(SysUserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    SysUserCredentials selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") SysUserCredentials record, @Param("example") SysUserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    int updateByExample(@Param("record") SysUserCredentials record, @Param("example") SysUserCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    int updateByPrimaryKeySelective(SysUserCredentials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_credentials
     *
     * @date
     */
    int updateByPrimaryKey(SysUserCredentials record);
}