package com.airlenet.play.website.mapper;

import com.airlenet.play.website.model.TblPluginConfigAttribute;
import com.airlenet.play.website.model.TblPluginConfigAttributeExample;
import com.airlenet.play.website.model.TblPluginConfigAttributeKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TblPluginConfigAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    long countByExample(TblPluginConfigAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    int deleteByExample(TblPluginConfigAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    int deleteByPrimaryKey(TblPluginConfigAttributeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    int insert(TblPluginConfigAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    int insertSelective(TblPluginConfigAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    List<TblPluginConfigAttribute> selectByExample(TblPluginConfigAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    TblPluginConfigAttribute selectByPrimaryKey(TblPluginConfigAttributeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") TblPluginConfigAttribute record, @Param("example") TblPluginConfigAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    int updateByExample(@Param("record") TblPluginConfigAttribute record, @Param("example") TblPluginConfigAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    int updateByPrimaryKeySelective(TblPluginConfigAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_plugin_config_attribute
     *
     * @date
     */
    int updateByPrimaryKey(TblPluginConfigAttribute record);
}