package com.airshiplay.play.website.mapper;

import com.airshiplay.play.website.model.CmsAdPosition;
import com.airshiplay.play.website.model.CmsAdPositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsAdPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    long countByExample(CmsAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    int deleteByExample(CmsAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    int insert(CmsAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    int insertSelective(CmsAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    List<CmsAdPosition> selectByExampleWithBLOBs(CmsAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    List<CmsAdPosition> selectByExample(CmsAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    CmsAdPosition selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") CmsAdPosition record, @Param("example") CmsAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    int updateByExampleWithBLOBs(@Param("record") CmsAdPosition record, @Param("example") CmsAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    int updateByExample(@Param("record") CmsAdPosition record, @Param("example") CmsAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    int updateByPrimaryKeySelective(CmsAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    int updateByPrimaryKeyWithBLOBs(CmsAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_ad_position
     *
     * @date
     */
    int updateByPrimaryKey(CmsAdPosition record);
}