package com.airshiplay.play.website.mapper;

import com.airshiplay.play.website.model.CmsArticleToTagExample;
import com.airshiplay.play.website.model.CmsArticleToTagKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsArticleToTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    long countByExample(CmsArticleToTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    int deleteByExample(CmsArticleToTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    int deleteByPrimaryKey(CmsArticleToTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    int insert(CmsArticleToTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    int insertSelective(CmsArticleToTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    List<CmsArticleToTagKey> selectByExample(CmsArticleToTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") CmsArticleToTagKey record, @Param("example") CmsArticleToTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_to_tag
     *
     * @date
     */
    int updateByExample(@Param("record") CmsArticleToTagKey record, @Param("example") CmsArticleToTagExample example);
}