package com.airshiplay.play.website.mapper;

import com.airshiplay.play.website.model.CmsQuestion;
import com.airshiplay.play.website.model.CmsQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    long countByExample(CmsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    int deleteByExample(CmsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    int insert(CmsQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    int insertSelective(CmsQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    List<CmsQuestion> selectByExampleWithBLOBs(CmsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    List<CmsQuestion> selectByExample(CmsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    CmsQuestion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") CmsQuestion record, @Param("example") CmsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    int updateByExampleWithBLOBs(@Param("record") CmsQuestion record, @Param("example") CmsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    int updateByExample(@Param("record") CmsQuestion record, @Param("example") CmsQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    int updateByPrimaryKeySelective(CmsQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    int updateByPrimaryKeyWithBLOBs(CmsQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_question
     *
     * @date
     */
    int updateByPrimaryKey(CmsQuestion record);
}