package com.airshiplay.play.website.mapper;

import com.airshiplay.play.website.model.ShopProduct;
import com.airshiplay.play.website.model.ShopProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    long countByExample(ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    int deleteByExample(ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    int insert(ShopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    int insertSelective(ShopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    List<ShopProduct> selectByExampleWithBLOBs(ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    List<ShopProduct> selectByExample(ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    ShopProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") ShopProduct record, @Param("example") ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    int updateByExampleWithBLOBs(@Param("record") ShopProduct record, @Param("example") ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    int updateByExample(@Param("record") ShopProduct record, @Param("example") ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    int updateByPrimaryKeySelective(ShopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    int updateByPrimaryKeyWithBLOBs(ShopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @date
     */
    int updateByPrimaryKey(ShopProduct record);
}