package com.airshiplay.play.website.mapper;

import com.airshiplay.play.website.model.WechatMessage;
import com.airshiplay.play.website.model.WechatMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    long countByExample(WechatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    int deleteByExample(WechatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    int insert(WechatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    int insertSelective(WechatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    List<WechatMessage> selectByExampleWithBLOBs(WechatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    List<WechatMessage> selectByExample(WechatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    WechatMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") WechatMessage record, @Param("example") WechatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    int updateByExampleWithBLOBs(@Param("record") WechatMessage record, @Param("example") WechatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    int updateByExample(@Param("record") WechatMessage record, @Param("example") WechatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    int updateByPrimaryKeySelective(WechatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    int updateByPrimaryKeyWithBLOBs(WechatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_message
     *
     * @date
     */
    int updateByPrimaryKey(WechatMessage record);
}