package com.airshiplay.play.website.mapper;

import com.airshiplay.play.website.model.WechatCardCoupon;
import com.airshiplay.play.website.model.WechatCardCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatCardCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    long countByExample(WechatCardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    int deleteByExample(WechatCardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    int insert(WechatCardCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    int insertSelective(WechatCardCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    List<WechatCardCoupon> selectByExample(WechatCardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    WechatCardCoupon selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") WechatCardCoupon record, @Param("example") WechatCardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    int updateByExample(@Param("record") WechatCardCoupon record, @Param("example") WechatCardCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    int updateByPrimaryKeySelective(WechatCardCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_card_coupon
     *
     * @date
     */
    int updateByPrimaryKey(WechatCardCoupon record);
}