package com.airshiplay.play.website.mapper;

import com.airshiplay.play.website.model.WechatImgtextTemplate;
import com.airshiplay.play.website.model.WechatImgtextTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatImgtextTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    long countByExample(WechatImgtextTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    int deleteByExample(WechatImgtextTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    int insert(WechatImgtextTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    int insertSelective(WechatImgtextTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    List<WechatImgtextTemplate> selectByExample(WechatImgtextTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    WechatImgtextTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") WechatImgtextTemplate record, @Param("example") WechatImgtextTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    int updateByExample(@Param("record") WechatImgtextTemplate record, @Param("example") WechatImgtextTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    int updateByPrimaryKeySelective(WechatImgtextTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_template
     *
     * @date
     */
    int updateByPrimaryKey(WechatImgtextTemplate record);
}