package com.airshiplay.play.website.mapper;

import com.airshiplay.play.website.model.WechatImgtextItem;
import com.airshiplay.play.website.model.WechatImgtextItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatImgtextItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    long countByExample(WechatImgtextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    int deleteByExample(WechatImgtextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    int insert(WechatImgtextItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    int insertSelective(WechatImgtextItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    List<WechatImgtextItem> selectByExample(WechatImgtextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    WechatImgtextItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") WechatImgtextItem record, @Param("example") WechatImgtextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    int updateByExample(@Param("record") WechatImgtextItem record, @Param("example") WechatImgtextItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    int updateByPrimaryKeySelective(WechatImgtextItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_imgtext_item
     *
     * @date
     */
    int updateByPrimaryKey(WechatImgtextItem record);
}