package com.airshiplay.play.website.mapper;

import com.airshiplay.play.website.model.WechatAttentionUser;
import com.airshiplay.play.website.model.WechatAttentionUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatAttentionUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    long countByExample(WechatAttentionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    int deleteByExample(WechatAttentionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    int insert(WechatAttentionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    int insertSelective(WechatAttentionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    List<WechatAttentionUser> selectByExample(WechatAttentionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    WechatAttentionUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") WechatAttentionUser record, @Param("example") WechatAttentionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    int updateByExample(@Param("record") WechatAttentionUser record, @Param("example") WechatAttentionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    int updateByPrimaryKeySelective(WechatAttentionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_user
     *
     * @date
     */
    int updateByPrimaryKey(WechatAttentionUser record);
}