package com.airshiplay.play.website.mapper;

import com.airshiplay.play.website.model.WechatAttentionReply;
import com.airshiplay.play.website.model.WechatAttentionReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatAttentionReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    long countByExample(WechatAttentionReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    int deleteByExample(WechatAttentionReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    int insert(WechatAttentionReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    int insertSelective(WechatAttentionReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    List<WechatAttentionReply> selectByExample(WechatAttentionReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    WechatAttentionReply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    int updateByExampleSelective(@Param("record") WechatAttentionReply record, @Param("example") WechatAttentionReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    int updateByExample(@Param("record") WechatAttentionReply record, @Param("example") WechatAttentionReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    int updateByPrimaryKeySelective(WechatAttentionReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_attention_reply
     *
     * @date
     */
    int updateByPrimaryKey(WechatAttentionReply record);
}